name: Playwright issue creator
description: This GitHub Action creates issues for failed tests in Playwright.
author: Elio Struyf <elio@struyfconsulting.be>

branding:
  icon: alert-circle
  color: red

inputs:
  github-token:
    description: 'The GitHub token to create the issues.'
    required: false
    default: ${{ github.token }}
  report-path:
    description: 'The path to the Playwright report file.'
    required: true
  issue-prefix:
    description: 'The prefix for the issue title.'
    required: false
  issue-labels:
    description: 'The labels to add to the issue (comma-separated).'
    required: false
  issue-footer:
    description: 'The footer to add to the issue.'
    required: false
    default: '> This issue was created by the Playwright issue creator action.'
  issue-assignees:
    description: 'The assignees to add to the issue (comma-separated).'
    required: false
  add-project-label:
    description: 'Add the project label to the issue.'
    required: false
  add-comment:
    description: 'Add a comment to the issue if the issue already exists.'
    required: false
  job-summary:
    description: 'Add the issue information to the job summary.'
    required: false
  quite:
    description: 'Do not log the issue creation.'
    required: false

runs:
  using: node20
  main: dist/index.js
