export const VARIABLES = {
  githubToken: "github-token",
  reportPath: "report-path",
  issuePrefix: "issue-prefix",
  issueLabels: "issue-labels",
  issueAssignees: "issue-assignees",
  issueFooter: "issue-footer",
  addProjectLabel: "add-project-label",
  addComment: "add-comment",
  closeOnSuccess: "close-on-success",
  closeOnSuccessMsg: "close-on-success-msg",
  jobSummary: "job-summary",
  quite: "quite",
  azureContainerUrl: "azure_container_url",
  azureContainerSas: "azure_container_sas",
};
